=== ITxPT/schematest/identifiers/example-globally_unique_id_value_test.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://raw.githubusercontent.com/ITxPT/schematest/main/identifiers/example-globally_unique_id_value_test.schema.json",
	"title": "Global Unique Identifier",
	"description": "ITxPT schema for Global Unique Identifier for any vehicle mode",
	"type": "object",
	"required": [
	    	"schema-link",
		"version",
		"atDateTime",
		"origin",
		"identifier"
	],
	"properties": {
		"schema-link": {
			"type": "string"
		},
		"$id":{
			"type": "string"
		},
		"version": {
			"description": "The ITxPT version number that the payload origins from",
			"type": "string",
			"minLength": 5,
			"maxLength": 14,
			"pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
		},
		"atDateTime": {
			"description": "TR-001 formated timestamp of when payload was generated",
			"type": "string",
			"format": "date-time"
		},
		"origin":{
	        	"type": "string",
            		"minLength": 3,
            		"maxLength": 16,
            		"pattern": "^[LRS]{1}-[a-zA-Z0-9]"
		},
		"identifier":{
			"description": "generic object for identifier",
		    	"type": "object",
            	"properties" :{
                	"idType": {
		        	"type": "string",
		        	"enum": ["VIN","UUID","EUI64"]
		        }
                },
		"required": [
	        	"idType",
		        "idValue"
        	],
        	"unevaluatedProperties": false,
        	"allOf": [
                	{
        	        	"if": {
        	        		"properties": {
        	                		"idType": {
        	                    		"type": "string",
        	                    		"const": "VIN"
        	                		}    
            	        		},
            	        		"required": ["idType"]
            	    		},
                		"then": {
               	        		"properties": {
            	            			"idValue":{
            	                			"description": "Vehicle Identification Number per ISO 3779:2009",
                                			"type": "string",
                                			"pattern": "^[A-Z0-9]{11,17}$"
        	                		}
        	            		}
             	    		}
                	},
                	{
        	        	"if": {
        	        		"properties": {
        	                		"idType": {
        	                    			"type": "string",
        	                    			"const": "UUID"
        	                		}    
            	        		},
            	        		"required": ["idType"]
            	    		},
            	    		"then": {
               	        		"properties": {
            	            			"idValue":{
            	                			"description": "Universally unique identifier (UUID) per ISO/IEC 9834-8:2005",
                                			"type": "string",
                                			"pattern": "^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$"
        	                		}
        	            		}
             	    		}
                	},
                	{
        	        	"if": {
        	        		"properties": {
        	                		"idType": {
        	                    			"type": "string",
        	                    			"const": "EUI64"
        	                		}    
            	        		},
            	        		"required": ["idType"]
            	    		},
            	    		"then": {
               	        		"properties": {
            	            			"idValue":{
            	                			"description": "IEEE 64-bit Global Identifier (EUI-64)",
                                			"type": "string",
                                			"pattern": "^([a-f0-9]{2}-){7}[a-f0-9]{2}$"
        	                		}
        	            		}
             	    		}
			}
        	]
		},
		"extensions": {
	    		"type": ["object", "array"],
		     	"required": [
				"origin"
			],
			"properties": {
				"origin": {
					"description": "A ITxPT formatted local identifier of the origin of the extension",
					"type": "string",
					"minLength": 3,
					"maxLength": 16,
					"pattern": "^[LRS]{1}-[a-zA-Z0-9]"
				}
			}
	    	}
	},
	"additionalProperties": false
}

=== ITxPT/schematest/identifiers/example2-vehicleid-VIN.json
{
	"schema-link":"https://raw.githubusercontent.com/ITxPT/schematest/main/identifiers/example-globally_unique_id_value_test.schema.json",
	"version": "2.3.0",
	"atDateTime": "2022-02-14T12:45:50Z",
	"origin": "L-Test01",
	"identifier": {
	    "idType": "VIN",
	    "idValue": "1GNDT13X53K185279"
	}
}

=== ITxPT/schematest/identifiers/example2-vehicleid-EUI64.json
{
	"schema-link": "https://raw.githubusercontent.com/ITxPT/schematest/main/identifiers/example-globally_unique_id_value_test.schema.json",
	"version": "2.3.0",
	"atDateTime": "2022-02-14T12:45:50Z",
	"origin": "L-Test03",
	"identifier": {
	    "idType": "EUI64",
	    "idValue": "00-00-7c-5c-f8-ef-d5-0d"
	}
}
